version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ms-lambda-bot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1a44qnx1odbgt"
s3_prefix = "ms-lambda-bot"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
