AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ms-lambda-bot

  Sample SAM Template for ms-lambda-bot
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15
Parameters:
  MicrosoftAppId:
      Type: String
  MicrosoftAppPassword:
      Type: String
  BotId:
      Type: String
  BotAliasId:
      Type: String            
  ENV:
      Type: String
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Timeout: 300
      MemorySize: 128
      PackageType: Zip
      Architectures:
        - x86_64
      Environment:
        Variables:
          MicrosoftAppId: !Sub "${MicrosoftAppId}"
          MicrosoftAppPassword: !Sub "${MicrosoftAppPassword}"
          BOT_ID: !Sub "${BotId}"
          BOT_ALIAS_ID: !Sub "${BotAliasId}"
          LOCALE_ID: en_US
          ENV: !Sub "${ENV}"
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/{proxy+}/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
